// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppResources.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppResources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: app-oer-catalog/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for AppResources (scope: System.App)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppResources data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.AllResources`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.App.
  /// </remarks>
  public partial class AppResources: AutoGenerated.ZAutoGenAppResources
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'AppResources' in scope 'System.App'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAppResources: Custom.Data.CustomItem
  {
    /// <summary>
    /// AllResources as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("AllResources", scrubHtml: true) etc.
    /// </summary>
    public string AllResources => _item.String("AllResources", fallback: "");

    /// <summary>
    /// Assets as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Assets", scrubHtml: true) etc.
    /// </summary>
    public string Assets => _item.String("Assets", fallback: "");

    /// <summary>
    /// Categories as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Categories", scrubHtml: true) etc.
    /// </summary>
    public string Categories => _item.String("Categories", fallback: "");

    /// <summary>
    /// ContactInfo as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ContactInfo", scrubHtml: true) etc.
    /// </summary>
    public string ContactInfo => _item.String("ContactInfo", fallback: "");

    /// <summary>
    /// Contributors as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Contributors", scrubHtml: true) etc.
    /// </summary>
    public string Contributors => _item.String("Contributors", fallback: "");

    /// <summary>
    /// Copyright as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Copyright", scrubHtml: true) etc.
    /// </summary>
    public string Copyright => _item.String("Copyright", fallback: "");

    /// <summary>
    /// Document as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Document", scrubHtml: true) etc.
    /// </summary>
    public string Document => _item.String("Document", fallback: "");

    /// <summary>
    /// EducationResources as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("EducationResources", scrubHtml: true) etc.
    /// </summary>
    public string EducationResources => _item.String("EducationResources", fallback: "");

    /// <summary>
    /// EduResource as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("EduResource", scrubHtml: true) etc.
    /// </summary>
    public string EduResource => _item.String("EduResource", fallback: "");

    /// <summary>
    /// Image as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Image", scrubHtml: true) etc.
    /// </summary>
    public string Image => _item.String("Image", fallback: "");

    /// <summary>
    /// Link as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Link", scrubHtml: true) etc.
    /// </summary>
    public string Link => _item.String("Link", fallback: "");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");

    /// <summary>
    /// SelectCategory as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SelectCategory", scrubHtml: true) etc.
    /// </summary>
    public string SelectCategory => _item.String("SelectCategory", fallback: "");

    /// <summary>
    /// SelectCopyright as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SelectCopyright", scrubHtml: true) etc.
    /// </summary>
    public string SelectCopyright => _item.String("SelectCopyright", fallback: "");

    /// <summary>
    /// SelectLanguage as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SelectLanguage", scrubHtml: true) etc.
    /// </summary>
    public string SelectLanguage => _item.String("SelectLanguage", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Translations as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Translations", scrubHtml: true) etc.
    /// </summary>
    public string Translations => _item.String("Translations", fallback: "");

    /// <summary>
    /// Video as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Video", scrubHtml: true) etc.
    /// </summary>
    public string Video => _item.String("Video", fallback: "");
  }
}