// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Asset.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Asset
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: app-oer-catalog/
// User:        2sic Web-Developer
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Asset 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Asset data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Description`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Asset: AutoGenerated.ZAutoGenAsset
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'Asset' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAsset: Custom.Data.CustomItem
  {
    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _item.String("Description", fallback: "");

    /// <summary>
    /// Label as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Label", scrubHtml: true) etc.
    /// </summary>
    public string Label => _item.String("Label", fallback: "");

    /// <summary>
    /// Link as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Link")
    /// </summary>
    public string Link => _item.Url("Link");

    /// <summary>
    /// Get the file object for Link - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LinkFile => _item.File("Link");

    /// <summary>
    /// Get the folder object for Link.
    /// </summary>

    [JsonIgnore]
    public IFolder LinkFolder => _item.Folder("Link");

    /// <summary>
    /// LinkType as single item of LinkType.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type LinkType was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public LinkType LinkType => _linkType ??= _item.Child<LinkType>("LinkType");
    private LinkType _linkType;
  }
}