// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "OpenEduResource.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class OpenEduResource
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: app-oer-catalog/
// User:        2sic Web-Developer
using System.Collections.Generic;
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for OpenEduResource 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// OpenEduResource data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Assets`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class OpenEduResource: AutoGenerated.ZAutoGenOpenEduResource
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'OpenEduResource' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenOpenEduResource: Custom.Data.CustomItem
  {
    /// <summary>
    /// Assets as list of Asset.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Asset was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Asset> Assets => _assets ??= _item.Children<Asset>("Assets");
    private IEnumerable<Asset> _assets;

    /// <summary>
    /// Categories as list of Category.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Category was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Category> Categories => _categories ??= _item.Children<Category>("Categories");
    private IEnumerable<Category> _categories;

    /// <summary>
    /// Contributors as list of Person.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Person was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Person> Contributors => _contributors ??= _item.Children<Person>("Contributors");
    private IEnumerable<Person> _contributors;

    /// <summary>
    /// Copyright as list of Copyright.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Copyright was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Copyright> Copyright => _copyright ??= _item.Children<Copyright>("Copyright");
    private IEnumerable<Copyright> _copyright;

    /// <summary>
    /// Description as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Description", scrubHtml: true) etc.
    /// </summary>
    public string Description => _item.String("Description", fallback: "");

    /// <summary>
    /// Preview as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Preview")
    /// </summary>
    public string Preview => _item.Url("Preview");

    /// <summary>
    /// Get the file object for Preview - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile PreviewFile => _item.File("Preview");

    /// <summary>
    /// Get the folder object for Preview.
    /// </summary>

    [JsonIgnore]
    public IFolder PreviewFolder => _item.Folder("Preview");

    /// <summary>
    /// Teaser as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Teaser", scrubHtml: true) etc.
    /// </summary>
    public string Teaser => _item.String("Teaser", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Translations as list of Language.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Language was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Language> Translations => _translations ??= _item.Children<Language>("Translations");
    private IEnumerable<Language> _translations;
  }
}