// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Person.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Person
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: app-oer-catalog/
// User:        2sic Web-Developer
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Person 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Person data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Biography`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Person: AutoGenerated.ZAutoGenPerson
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'Person' in scope 'Default'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenPerson: Custom.Data.CustomItem
  {
    /// <summary>
    /// Biography as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Biography", scrubHtml: true) etc.
    /// </summary>
    public string Biography => _item.String("Biography", fallback: "");

    /// <summary>
    /// ContactInfo as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ContactInfo", scrubHtml: true) etc.
    /// </summary>
    public string ContactInfo => _item.String("ContactInfo", fallback: "");

    /// <summary>
    /// CopyrightAgreement as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("CopyrightAgreement")
    /// </summary>
    public string CopyrightAgreement => _item.Url("CopyrightAgreement");

    /// <summary>
    /// Get the file object for CopyrightAgreement - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile CopyrightAgreementFile => _item.File("CopyrightAgreement");

    /// <summary>
    /// Get the folder object for CopyrightAgreement.
    /// </summary>

    [JsonIgnore]
    public IFolder CopyrightAgreementFolder => _item.Folder("CopyrightAgreement");

    /// <summary>
    /// CopyrightDefault as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("CopyrightDefault", scrubHtml: true) etc.
    /// </summary>
    public string CopyrightDefault => _item.String("CopyrightDefault", fallback: "");

    /// <summary>
    /// Link as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Link", scrubHtml: true) etc.
    /// </summary>
    public string Link => _item.String("Link", fallback: "");

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");

    /// <summary>
    /// NameVisible as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NameVisible", scrubHtml: true) etc.
    /// </summary>
    public string NameVisible => _item.String("NameVisible", fallback: "");

    /// <summary>
    /// Photo as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Photo")
    /// </summary>
    public string Photo => _item.Url("Photo");

    /// <summary>
    /// Get the file object for Photo - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile PhotoFile => _item.File("Photo");

    /// <summary>
    /// Get the folder object for Photo.
    /// </summary>

    [JsonIgnore]
    public IFolder PhotoFolder => _item.Folder("Photo");
  }
}